### PR TITLE
Small fixes to make it compile on latest versions of Nim

### PR DESCRIPTION
**Pull request by dom96**
I couldn't get the `toPy` converter to work so I turned it into a proc for now.

### CODE REVIEW

**Comment by Araq** [comment]
Why not use my fork of it instead?

**Comment by micklat** [comment]
I'm not working on this project anymore. Guess I'll take it off github, and maybe leave a note pointing people to Arak's fork, unless you have a better idea.

**Comment by dom96** [comment]
Don't remove the code, just add a link to Araq's fork in the readme.

**Comment by dom96** [comment]
I'll close this since Araq's fork has better changes.

**Pull request closed without merging**
